[tools]
node = "24.14.1"
pnpm = "10.5.2"
viteplus = "0.1.15"

[env]
_.path = ["F:/Apps/Git/usr/bin"]

[tasks]
install = "vp install"
clean   = "rm -rf .nuxt .output node_modules pnpm-lock.yaml"

[tasks.all]
depends = ["install"]
run = "vp exec portless nhankiet vp exec nuxi dev"
